-- 2022년 1월 도서판매 데이터 기준
-- 저자 별, 카테고리 별 매출액
-- 저자 ID, 저자명, 카테고리, 매출액 리스트 출력
-- 저자 ID 기준 오름차순
-- 같다면 카테고리 기준 내림차순

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK AS B 
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01-%'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
;