-- 우유(Milk)와 요거트(Yogurt)를 동시에 구입한 장바구니 아이디를 조회
-- 아이디를 ASC 순서

SELECT DISTINCT(CART_ID) AS CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
    ) 
    AND CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
    )
ORDER BY CART_ID ASC
;