-- ROOT 아이템이 없는 경우는 존재하지 않는다.

# SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
# FROM ITEM_INFO AS INFO JOIN ITEM_TREE AS TREE
# WHERE INFO.ITEM_ID IN (
#     SELECT T.ITEM_ID
#     FROM ITEM_INFO AS I JOIN ITEM_TREE AS T 
#     ON I.ITEM_ID = T.PARENT_ITEM_ID
# )
# AND INFO.ITEM_ID NOT IN (T.PARENT_ITEM_ID)
# ORDER BY INFO.ITEM_ID DESC

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO 
WHERE ITEM_ID NOT IN (
    SELECT DISTINCT PARENT_ITEM_ID 
    FROM ITEM_TREE 
    WHERE PARENT_ITEM_ID IS NOT NULL 
)
ORDER BY ITEM_ID DESC
