-- 2022년 3월
-- 오프라인&온라인 상품판매 데이터
-- 판매 날짜, 상품ID, 유저ID, 판매량을 출력
-- 판매일 기준으로 오름차순
-- 판매일이 같다면 상품 ID를 기준으로 오름차순
-- 상품 ID까지 같다면 유저 ID를 기준으로 오름차순

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03-%'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03-%'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC 