-- 중고 거래 게시물을 3건 이상 등록한 사용자
-- 사용자 ID, 닉네임, 전체주소, 전화번호 조회
-- 전체주소 : 시, 도로명 주소, 상세 주소가 함께 출력
-- 전화버호 : XXX-XXXX-XXXX
-- 회원 ID를 기준으로 내림차순

SELECT U.USER_ID, U.NICKNAME, 
CONCAT(U.CITY, ' ',U.STREET_ADDRESS1, ' ',U.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTRING(TLNO,1,3), '-', SUBSTRING(TLNO,4,4), '-', SUBSTRING(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
WHERE U.USER_ID IN (
        SELECT WRITER_ID FROM USED_GOODS_BOARD 
        GROUP BY WRITER_ID
        HAVING COUNT(WRITER_ID) >= 3
)
GROUP BY U.USER_ID
ORDER BY U.USER_ID DESC
;