-- 년, 월, 성별 기준으로 오름차순 정렬
-- 성별 정보가 없는 경우 결과에서 제외

# SELECT DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR, DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH,
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
    U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO AS U JOIN ONLINE_SALE AS S ON U.USER_ID = S.USER_ID
WHERE U.GENDER = 0 OR U.GENDER = 1
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER 
