-- 자동차 ID와 AVAILABILITY 리스트를 출력
-- 자동차 ID를 기준으로 내림차순 정렬
# SELECT
#     CAR_ID,
#     (CASE  
#         WHEN CAR_ID IN ( SELECT CAR_ID 
#                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                     WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
#                    ) THEN '대여 중'
#         ELSE '대여 가능' 
#         END 
#     ) AS AVAILABILITY 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC
# ;

SELECT CAR_ID, 
    (CASE 
        WHEN CAR_ID IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE 
        ) THEN '대여중' 
    ELSE '대여 가능' 
    END
    ) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC