-- 생산일자가 2022년 5월
-- 식품 ID, 식품 이름, 총매출을 조회
-- 총매출 기준으로 내림차순
-- 같다면 식품 ID를 기준 오름차순 정렬

# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.AMOUNT) AS TOTAL_SALES 
# FROM FOOD_PRODUCT AS P JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE O.PRODUCE_DATE LIKE "2022-05-%"
# GROUP BY P.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P JOIN (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
        FROM FOOD_ORDER
        WHERE PRODUCE_DATE LIKE "2022-05-%"
        GROUP BY PRODUCT_ID
    ) AS O 
    ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC
