# 상품코드 별 매출액(판매가 x 판매량)의 합계
# 매출액 기준 내림차순
# 매출액이 같으면 상품코드 기준 오름차순
SELECT X.PRODUCT_CODE AS PRODUCT_CODE, SUM(X.PRICE * Y.SALES_AMOUNT) AS SALES 
FROM PRODUCT X JOIN OFFLINE_SALE Y
ON X.PRODUCT_ID = Y.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
;