-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해
-- 기록 별로 대여 금액(컬럼명: FEE)을 구하여 
-- 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문
-- 대여 금액 DESC -> 대여 기록 ID DESC


# COALESCE(P.DISCOUNT_RATE, 0)은 P.DISCOUNT_RATE가 NULL이 아니면 P.DISCOUNT_RATE를, NULL이면 0을 반환
SELECT H.HISTORY_ID, 
    ROUND((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE *  (1 - COALESCE(P.DISCOUNT_RATE, 0) * 0.01)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID
# 할인이 없는 NULL인 경우때문에 LEFT JOIN
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE
    AND (
        CASE 
            WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE,H.START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE NULL
        END
    ) = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'      
ORDER BY FEE DESC, HISTORY_ID DESC
;