SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
WHERE D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'JavaScript') > 0
    OR D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'React') > 0
    OR D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Vue') > 0
ORDER BY D.ID ASC;
