-- 생일이 3월 / 여성 회원 
-- ID, 이름, 성별, 생년월일을 조회
-- 전화번호 NULL 제외
-- ID 기준 ASC

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '%-03-%' 
    AND GENDER = 'W'
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC
;