-- 대여시작일 기준 2022년 8월 ~ 2022년 10월
-- 총 대여 횟수가 5회 이상
-- 해당 기간동안의 월별 자동차 ID 별 총 대여 횟수 (RECORDS) 출력
-- 월을 기준으로 오름차순 정렬 == > 자동차 ID 기준 내림차순
-- 특정 월의 총 대여 횟수가 0이 경우 결과에서 제외

SELECT MONTH(START_DATE) AS MONTH,  CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE START_DATE LIKE '2022-08-%' OR START_DATE LIKE '2022-09-%' OR START_DATE LIKE '2022-10-%'
WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
    AND CAR_ID IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5 
        )
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC
;