-- 총주문량이 3,000보다 높다 / 주 성분이 과일
-- 총주문량이 큰 순서대로 조회 (DESC)
SELECT H.FLAVOR
FROM FIRST_HALF AS H JOIN ICECREAM_INFO  AS I
    ON H.FLAVOR = I.FLAVOR
WHERE H.TOTAL_ORDER > 3000
    AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
;