-- 자동차 종류 = 세단
-- 10월에 대여를 시작한 기록
-- 자동차 ID 리스트를 출력
-- 중복 X, 자동차 ID 기준 DESC

SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE START_DATE LIKE "%-10-%" AND CAR_TYPE = "세단"
ORDER BY C.CAR_ID DESC
;