SELECT FI.ID, FNI.FISH_NAME, MAX_INFO.MAX_LENGTH AS LENGTH
FROM (
    SELECT FISH_TYPE, MAX(IF(LENGTH IS NULL, 10, LENGTH)) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) AS MAX_INFO
    JOIN FISH_INFO AS FI ON MAX_INFO.FISH_TYPE = FI.FISH_TYPE 
        AND MAX_INFO.MAX_LENGTH = IF(FI.LENGTH IS NULL, 10, FI.LENGTH)
    JOIN FISH_NAME_INFO AS FNI ON MAX_INFO.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID ASC
;