-- 2021년에 출판 / '인문' 카테고리
-- 도서 ID, 출판일(PUBLISHED_DATE) 출력
-- 출판일 기준 ASC

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK 
WHERE PUBLISHED_DATE LIKE '2021-%'
    AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC
;