-- 아이스크림의 총주문량을 총주문량이 작은 순서대로 조회
SELECT INGREDIENT_TYPE, SUM(H.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS H JOIN ICECREAM_INFO AS I
    ON H.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
;