-- 상반기 아이스크림 성분 타입, 성분 타입에 대한 아이스크림 총주문량 출력
-- 총 주문량이 작은 순서
-- 총 주문량을 나타내는 컬럼명은 TOTAL_ORDER로 지정

SELECT INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS A JOIN ICECREAM_INFO AS B ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER