-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고
-- 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력
-- 카테고리명을 기준으로 오름차순
SELECT CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B JOIN (
    SELECT *
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01-%'
    ) AS S
    ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
;